name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    # Client setup and start
    - name: Install client dependencies
      working-directory: ./client
      run: npm ci --legacy-peer-deps

    - name: Build client
      working-directory: ./client
      run: CI=false npm run build --if-present

    - name: Start client
      working-directory: ./client
      run: npm start &

    # Server setup and start
    - name: Install server dependencies
      working-directory: ./server
      run: npm ci --legacy-peer-deps

    - name: Start server
      working-directory: ./server
      run: npm run &

    # Run tests
    - name: Run client tests
      working-directory: ./client
      run: npm test

    - name: Run server tests
      working-directory: ./server
      run: npm test
